services:
  db:
    image: postgres:16-alpine3.20
    restart: always
    env_file:
      - ./db/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./db/pgadmin.env
    ports:
      - 5050:80
    volumes:
      - ./db/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgadmin_data:
